### ISSUE TITLE
alternative line separator detection method

### ISSUE THREAD

**Issue by bjmi** [cypher256/eclipse-encoding-plugin#1]
I don't know a better way to get in contact with you therefore I create this issue.

May be you could give this line separator detection a try https://gist.github.com/bjmi/7b2b0bca9470e9a3b624d0eb3cd41f98

**Comment by cypher256** [comment]
It was improved based on your code.
https://gist.github.com/cypher256/f4b1dca724ff72132a042cea84926db2

Does not support line ending following. Because Eclipse editor unrecognized them.
- NEL, NEW LINE U+0085
- VT, VERTICAL TAB  U+0008
- FF, FORM FEED U+000C
- LS, LINE SEPARATOR    U+2028
- PS, PARAGRAPH SEPARATOR   U+2029
